package com.twisted.enum.common

val QueuesDto = mapOf<Int, String>(
    2 to "5v5 Blind Pick games",
    4 to "5v5 Ranked Solo games",
    6 to "5v5 Ranked Premade games",
    7 to "Co-op vs AI games",
    8 to "3v3 Normal games",
    9 to "3v3 Ranked Flex games",
    14 to "5v5 Draft Pick games",
    16 to "5v5 Dominion Blind Pick games",
    17 to "5v5 Dominion Draft Pick games",
    25 to "Dominion Co-op vs AI games",
    31 to "Co-op vs AI Intro Bot games",
    32 to "Co-op vs AI Beginner Bot games",
    33 to "Co-op vs AI Intermediate Bot games",
    41 to "3v3 Ranked Team games",
    42 to "5v5 Ranked Team games",
    52 to "Co-op vs AI games",
    61 to "5v5 Team Builder games",
    65 to "5v5 ARAM games",
    67 to "ARAM Co-op vs AI games",
    70 to "One for All games",
    72 to "1v1 Snowdown Showdown games",
    73 to "2v2 Snowdown Showdown games",
    75 to "6v6 Hexakill games",
    76 to "Ultra Rapid Fire games",
    78 to "One For All: Mirror Mode games",
    83 to "Co-op vs AI Ultra Rapid Fire games",
    91 to "Doom Bots Rank 1 games",
    92 to "Doom Bots Rank 2 games",
    93 to "Doom Bots Rank 5 games",
    96 to "Ascension games",
    98 to "6v6 Hexakill games",
    100 to "5v5 ARAM games",
    300 to "Legend of the Poro King games",
    310 to "Nemesis games",
    313 to "Black Market Brawlers games",
    315 to "Nexus Siege games",
    317 to "Definitely Not Dominion games",
    318 to "ARURF games",
    325 to "All Random games",
    400 to "5v5 Draft Pick games",
    410 to "5v5 Ranked Dynamic games",
    420 to "5v5 Ranked Solo games",
    430 to "5v5 Blind Pick games",
    440 to "5v5 Ranked Flex games",
    450 to "5v5 ARAM games",
    460 to "3v3 Blind Pick games",
    470 to "3v3 Ranked Flex games",
    600 to "Blood Hunt Assassin games",
    610 to "Dark Star: Singularity games",
    700 to "Clash games",
    800 to "Co-op vs. AI Intermediate Bot games",
    810 to "Co-op vs. AI Intro Bot games",
    820 to "Co-op vs. AI Beginner Bot games",
    830 to "Co-op vs. AI Intro Bot games",
    840 to "Co-op vs. AI Beginner Bot games",
    850 to "Co-op vs. AI Intermediate Bot games",
    900 to "URF games",
    910 to "Ascension games",
    920 to "Legend of the Poro King games",
    940 to "Nexus Siege games",
    950 to "Doom Bots Voting games",
    960 to "Doom Bots Standard games",
    980 to "Star Guardian Invasion: Normal games",
    990 to "Star Guardian Invasion: Onslaught games",
    1000 to "PROJECT: Hunters games",
    1010 to "Snow ARURF games",
    1020 to "One for All games",
    1030 to "Odyssey Extraction: Intro games",
    1040 to "Odyssey Extraction: Cadet games",
    1050 to "Odyssey Extraction: Crewmember games",
    1060 to "Odyssey Extraction: Captain games",
    1070 to "Odyssey Extraction: Onslaught games",
    1090 to "Teamfight Tactics games",
    1100 to "Ranked Teamfight Tactics games",
    1200 to "Nexus Blitz games",
    2000 to "Tutorial 1",
    2010 to "Tutorial 2",
    2020 to "Tutorial 3"
)
